from __future__ import annotations

from collections.abc import Sequence

from sqlalchemy.orm import Session

from core.shared.db import UUIDv7
from core.supplier.models import Supplier
from core.supplier.repository import SupplierRepository
from core.supplier.schemas import SupplierCreate, SupplierUpdate
from core.supplier.supplier_code import SupplierCodeGenerator


class SupplierNotFoundError(Exception):
    """Raised when a supplier is missing or has been archived."""


class SupplierNameRequiredError(Exception):
    """Raised when a supplier name is empty after whitespace normalization."""


class SupplierService:
    """Business operations for reusable supplier reference data."""

    def __init__(self, session: Session) -> None:
        """Create a service using the given database session."""
        self._session = session
        self._repository = SupplierRepository(session)

    def register_supplier(
        self,
        data: SupplierCreate,
        *,
        actor_id: UUIDv7 | None = None,
    ) -> Supplier:
        """Register a supplier with a stable code generated by the system."""
        supplier = Supplier(
            name=self._normalize_required_name(data.name),
            display_name=self._normalize_display_name(data.display_name),
            notes=data.notes,
            is_active=data.is_active,
            code=SupplierCodeGenerator.generate(self._repository.reserve_next_supplier_code_number()),
            created_by_id=actor_id,
        )
        self._repository.add(supplier)
        self._session.commit()
        self._session.refresh(supplier)
        return supplier

    def list_suppliers(self) -> Sequence[Supplier]:
        """Return suppliers available for normal purchasing operations."""
        return self._repository.list()

    def get_supplier(self, supplier_id: UUIDv7) -> Supplier:
        """Return a non-archived supplier or raise a business error."""
        supplier = self._repository.get(supplier_id)
        if supplier is None:
            raise SupplierNotFoundError
        return supplier

    def update_supplier(
        self,
        supplier_id: UUIDv7,
        data: SupplierUpdate,
        *,
        actor_id: UUIDv7 | None = None,
    ) -> Supplier:
        """Update mutable supplier fields while preserving its system-generated code."""
        supplier = self.get_supplier(supplier_id)
        changes = data.model_dump(exclude_unset=True)
        if "name" in changes:
            supplier.name = self._normalize_required_name(data.name)
        if "display_name" in changes:
            supplier.display_name = self._normalize_display_name(data.display_name)
        if "notes" in changes:
            supplier.notes = data.notes
        if "is_active" in changes:
            supplier.is_active = data.is_active
        if actor_id is not None:
            supplier.updated_by_id = actor_id
        self._session.commit()
        self._session.refresh(supplier)
        return supplier

    def archive_supplier(self, supplier_id: UUIDv7, *, actor_id: UUIDv7 | None = None) -> None:
        """Soft-delete a supplier while retaining receiving history for future use."""
        supplier = self.get_supplier(supplier_id)
        supplier.soft_delete(actor_id)
        self._session.commit()

    def _normalize_required_name(self, value: str | None) -> str:
        """Trim and validate the required supplier legal or reference name."""
        normalized = (value or "").strip()
        if not normalized:
            raise SupplierNameRequiredError
        return normalized

    def _normalize_display_name(self, value: str | None) -> str | None:
        """Trim an optional display name while preserving null values."""
        if value is None:
            return None
        return value.strip()
